//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.WFCL.SRDepartment {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfArrayOfDepartmentdYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfArrayOfDepartmentdYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRDepartment.Department[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRDepartment.Department[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/LY.MES.Model")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DepBeginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DepEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupDepCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepAddress {
            get {
                return this.DepAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DepAddressField, value) != true)) {
                    this.DepAddressField = value;
                    this.RaisePropertyChanged("DepAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepBeginDate {
            get {
                return this.DepBeginDateField;
            }
            set {
                if ((this.DepBeginDateField.Equals(value) != true)) {
                    this.DepBeginDateField = value;
                    this.RaisePropertyChanged("DepBeginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepCode {
            get {
                return this.DepCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepCodeField, value) != true)) {
                    this.DepCodeField = value;
                    this.RaisePropertyChanged("DepCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepEmail {
            get {
                return this.DepEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.DepEmailField, value) != true)) {
                    this.DepEmailField = value;
                    this.RaisePropertyChanged("DepEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DepEndDate {
            get {
                return this.DepEndDateField;
            }
            set {
                if ((this.DepEndDateField.Equals(value) != true)) {
                    this.DepEndDateField = value;
                    this.RaisePropertyChanged("DepEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepFax {
            get {
                return this.DepFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.DepFaxField, value) != true)) {
                    this.DepFaxField = value;
                    this.RaisePropertyChanged("DepFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepMemo {
            get {
                return this.DepMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepMemoField, value) != true)) {
                    this.DepMemoField = value;
                    this.RaisePropertyChanged("DepMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepName {
            get {
                return this.DepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepNameField, value) != true)) {
                    this.DepNameField = value;
                    this.RaisePropertyChanged("DepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepPerson {
            get {
                return this.DepPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.DepPersonField, value) != true)) {
                    this.DepPersonField = value;
                    this.RaisePropertyChanged("DepPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepPhone {
            get {
                return this.DepPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.DepPhoneField, value) != true)) {
                    this.DepPhoneField = value;
                    this.RaisePropertyChanged("DepPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepPostCode {
            get {
                return this.DepPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepPostCodeField, value) != true)) {
                    this.DepPostCodeField = value;
                    this.RaisePropertyChanged("DepPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupDepCode {
            get {
                return this.SupDepCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupDepCodeField, value) != true)) {
                    this.SupDepCodeField = value;
                    this.RaisePropertyChanged("SupDepCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CustomFaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfDepartmentdYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfDepartmentdYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRDepartment.Department DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRDepartment.Department Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/LY.MES.Model")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OparatorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OparatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonEmaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepCode {
            get {
                return this.DepCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepCodeField, value) != true)) {
                    this.DepCodeField = value;
                    this.RaisePropertyChanged("DepCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOperator {
            get {
                return this.IsOperatorField;
            }
            set {
                if ((this.IsOperatorField.Equals(value) != true)) {
                    this.IsOperatorField = value;
                    this.RaisePropertyChanged("IsOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OparatorCode {
            get {
                return this.OparatorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OparatorCodeField, value) != true)) {
                    this.OparatorCodeField = value;
                    this.RaisePropertyChanged("OparatorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OparatorName {
            get {
                return this.OparatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OparatorNameField, value) != true)) {
                    this.OparatorNameField = value;
                    this.RaisePropertyChanged("OparatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonCode {
            get {
                return this.PersonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonCodeField, value) != true)) {
                    this.PersonCodeField = value;
                    this.RaisePropertyChanged("PersonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonEmai {
            get {
                return this.PersonEmaiField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonEmaiField, value) != true)) {
                    this.PersonEmaiField = value;
                    this.RaisePropertyChanged("PersonEmai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName {
            get {
                return this.PersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonNameField, value) != true)) {
                    this.PersonNameField = value;
                    this.RaisePropertyChanged("PersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonPhone {
            get {
                return this.PersonPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonPhoneField, value) != true)) {
                    this.PersonPhoneField = value;
                    this.RaisePropertyChanged("PersonPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonType {
            get {
                return this.PersonTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonTypeField, value) != true)) {
                    this.PersonTypeField = value;
                    this.RaisePropertyChanged("PersonType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfArrayOfPersondYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfArrayOfPersondYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRDepartment.Person[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRDepartment.Person[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfPersondYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfPersondYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRDepartment.Person DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRDepartment.Person Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRDepartment.IDepartmentService")]
    public interface IDepartmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartmentList", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/GetDepartmentListCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfDepartmentdYMi5huk GetDepartmentList(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartmentList", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentListResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfDepartmentdYMi5huk> GetDepartmentListAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/AddDepartmentData", ReplyAction="http://tempuri.org/IDepartmentService/AddDepartmentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/AddDepartmentDataCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk AddDepartmentData(string sessionId, LY.MES.WFCL.SRDepartment.Department Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/AddDepartmentData", ReplyAction="http://tempuri.org/IDepartmentService/AddDepartmentDataResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk> AddDepartmentDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Department Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/UpdataDepartmentData", ReplyAction="http://tempuri.org/IDepartmentService/UpdataDepartmentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/UpdataDepartmentDataCustomFaultMessageFault" +
            "", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk UpdataDepartmentData(string sessionId, LY.MES.WFCL.SRDepartment.Department Model, string strDepartmentNameOriginal, string strDepartmentNameNow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/UpdataDepartmentData", ReplyAction="http://tempuri.org/IDepartmentService/UpdataDepartmentDataResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk> UpdataDepartmentDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Department Model, string strDepartmentNameOriginal, string strDepartmentNameNow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/DelDepartmentData", ReplyAction="http://tempuri.org/IDepartmentService/DelDepartmentDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/DelDepartmentDataCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        Client.Utility.SRSysBase.CommonResultOfboolean DelDepartmentData(string sessionId, string strDepCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/DelDepartmentData", ReplyAction="http://tempuri.org/IDepartmentService/DelDepartmentDataResponse")]
        System.Threading.Tasks.Task<Client.Utility.SRSysBase.CommonResultOfboolean> DelDepartmentDataAsync(string sessionId, string strDepCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetPersonList", ReplyAction="http://tempuri.org/IDepartmentService/GetPersonListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/GetPersonListCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.Department[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.Department))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.Person[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.Person))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfDepartmentdYMi5huk))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Client.Utility.SRSysBase.CommonResultOfboolean))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfPersondYMi5huk))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfPersondYMi5huk GetPersonList(string sessionId, System.Tuple<string, object[]> tFilter, int PageSize, int CurrPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetPersonList", ReplyAction="http://tempuri.org/IDepartmentService/GetPersonListResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfPersondYMi5huk> GetPersonListAsync(string sessionId, System.Tuple<string, object[]> tFilter, int PageSize, int CurrPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/AddPersonData", ReplyAction="http://tempuri.org/IDepartmentService/AddPersonDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/AddPersonDataCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk AddPersonData(string sessionId, LY.MES.WFCL.SRDepartment.Person Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/AddPersonData", ReplyAction="http://tempuri.org/IDepartmentService/AddPersonDataResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk> AddPersonDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Person Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/UpdataPersonData", ReplyAction="http://tempuri.org/IDepartmentService/UpdataPersonDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/UpdataPersonDataCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk UpdataPersonData(string sessionId, LY.MES.WFCL.SRDepartment.Person Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/UpdataPersonData", ReplyAction="http://tempuri.org/IDepartmentService/UpdataPersonDataResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk> UpdataPersonDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Person Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/DelPersonData", ReplyAction="http://tempuri.org/IDepartmentService/DelPersonDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRDepartment.CustomFaultMessage), Action="http://tempuri.org/IDepartmentService/DelPersonDataCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        Client.Utility.SRSysBase.CommonResultOfboolean DelPersonData(string sessionId, LY.MES.WFCL.SRDepartment.Person Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/DelPersonData", ReplyAction="http://tempuri.org/IDepartmentService/DelPersonDataResponse")]
        System.Threading.Tasks.Task<Client.Utility.SRSysBase.CommonResultOfboolean> DelPersonDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Person Model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartmentServiceChannel : LY.MES.WFCL.SRDepartment.IDepartmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentServiceClient : System.ServiceModel.ClientBase<LY.MES.WFCL.SRDepartment.IDepartmentService>, LY.MES.WFCL.SRDepartment.IDepartmentService {
        
        public DepartmentServiceClient() {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfDepartmentdYMi5huk GetDepartmentList(string sessionId) {
            return base.Channel.GetDepartmentList(sessionId);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfDepartmentdYMi5huk> GetDepartmentListAsync(string sessionId) {
            return base.Channel.GetDepartmentListAsync(sessionId);
        }
        
        public LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk AddDepartmentData(string sessionId, LY.MES.WFCL.SRDepartment.Department Model) {
            return base.Channel.AddDepartmentData(sessionId, Model);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk> AddDepartmentDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Department Model) {
            return base.Channel.AddDepartmentDataAsync(sessionId, Model);
        }
        
        public LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk UpdataDepartmentData(string sessionId, LY.MES.WFCL.SRDepartment.Department Model, string strDepartmentNameOriginal, string strDepartmentNameNow) {
            return base.Channel.UpdataDepartmentData(sessionId, Model, strDepartmentNameOriginal, strDepartmentNameNow);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfDepartmentdYMi5huk> UpdataDepartmentDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Department Model, string strDepartmentNameOriginal, string strDepartmentNameNow) {
            return base.Channel.UpdataDepartmentDataAsync(sessionId, Model, strDepartmentNameOriginal, strDepartmentNameNow);
        }
        
        public Client.Utility.SRSysBase.CommonResultOfboolean DelDepartmentData(string sessionId, string strDepCode) {
            return base.Channel.DelDepartmentData(sessionId, strDepCode);
        }
        
        public System.Threading.Tasks.Task<Client.Utility.SRSysBase.CommonResultOfboolean> DelDepartmentDataAsync(string sessionId, string strDepCode) {
            return base.Channel.DelDepartmentDataAsync(sessionId, strDepCode);
        }
        
        public LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfPersondYMi5huk GetPersonList(string sessionId, System.Tuple<string, object[]> tFilter, int PageSize, int CurrPage) {
            return base.Channel.GetPersonList(sessionId, tFilter, PageSize, CurrPage);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfArrayOfPersondYMi5huk> GetPersonListAsync(string sessionId, System.Tuple<string, object[]> tFilter, int PageSize, int CurrPage) {
            return base.Channel.GetPersonListAsync(sessionId, tFilter, PageSize, CurrPage);
        }
        
        public LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk AddPersonData(string sessionId, LY.MES.WFCL.SRDepartment.Person Model) {
            return base.Channel.AddPersonData(sessionId, Model);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk> AddPersonDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Person Model) {
            return base.Channel.AddPersonDataAsync(sessionId, Model);
        }
        
        public LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk UpdataPersonData(string sessionId, LY.MES.WFCL.SRDepartment.Person Model) {
            return base.Channel.UpdataPersonData(sessionId, Model);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRDepartment.CommonResultOfPersondYMi5huk> UpdataPersonDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Person Model) {
            return base.Channel.UpdataPersonDataAsync(sessionId, Model);
        }
        
        public Client.Utility.SRSysBase.CommonResultOfboolean DelPersonData(string sessionId, LY.MES.WFCL.SRDepartment.Person Model) {
            return base.Channel.DelPersonData(sessionId, Model);
        }
        
        public System.Threading.Tasks.Task<Client.Utility.SRSysBase.CommonResultOfboolean> DelPersonDataAsync(string sessionId, LY.MES.WFCL.SRDepartment.Person Model) {
            return base.Channel.DelPersonDataAsync(sessionId, Model);
        }
    }
}
