//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.WFCL.SRPiPeline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainPipelineInfo", Namespace="http://schemas.datacontract.org/2004/07/LY.MES.Model")]
    [System.SerializableAttribute()]
    public partial class MainPipelineInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeveCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeveNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OperatingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorReamrkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PipelineStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromptDesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoID {
            get {
                return this.AutoIDField;
            }
            set {
                if ((this.AutoIDField.Equals(value) != true)) {
                    this.AutoIDField = value;
                    this.RaisePropertyChanged("AutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeveCode {
            get {
                return this.DeveCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveCodeField, value) != true)) {
                    this.DeveCodeField = value;
                    this.RaisePropertyChanged("DeveCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeveName {
            get {
                return this.DeveNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveNameField, value) != true)) {
                    this.DeveNameField = value;
                    this.RaisePropertyChanged("DeveName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((object.ReferenceEquals(this.FrequencyField, value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OperatingTime {
            get {
                return this.OperatingTimeField;
            }
            set {
                if ((this.OperatingTimeField.Equals(value) != true)) {
                    this.OperatingTimeField = value;
                    this.RaisePropertyChanged("OperatingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorReamrk {
            get {
                return this.OperatorReamrkField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorReamrkField, value) != true)) {
                    this.OperatorReamrkField = value;
                    this.RaisePropertyChanged("OperatorReamrk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PipelineStatus {
            get {
                return this.PipelineStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PipelineStatusField, value) != true)) {
                    this.PipelineStatusField = value;
                    this.RaisePropertyChanged("PipelineStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromptDes {
            get {
                return this.PromptDesField;
            }
            set {
                if ((object.ReferenceEquals(this.PromptDesField, value) != true)) {
                    this.PromptDesField = value;
                    this.RaisePropertyChanged("PromptDes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/LY.MES.Model")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatePersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevAbbNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevCCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DevCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevDefine11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevDefine12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DevDefine13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DevDefine14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DevDefine15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DevDefine16Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDefine9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevQRUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevStdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FContactsTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactoryContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminPerson {
            get {
                return this.AdminPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPersonField, value) != true)) {
                    this.AdminPersonField = value;
                    this.RaisePropertyChanged("AdminPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminPhone {
            get {
                return this.AdminPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPhoneField, value) != true)) {
                    this.AdminPhoneField = value;
                    this.RaisePropertyChanged("AdminPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CallID {
            get {
                return this.CallIDField;
            }
            set {
                if ((this.CallIDField.Equals(value) != true)) {
                    this.CallIDField = value;
                    this.RaisePropertyChanged("CallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatePerson {
            get {
                return this.CreatePersonField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatePersonField, value) != true)) {
                    this.CreatePersonField = value;
                    this.RaisePropertyChanged("CreatePerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevAbbName {
            get {
                return this.DevAbbNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DevAbbNameField, value) != true)) {
                    this.DevAbbNameField = value;
                    this.RaisePropertyChanged("DevAbbName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevCCode {
            get {
                return this.DevCCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DevCCodeField, value) != true)) {
                    this.DevCCodeField = value;
                    this.RaisePropertyChanged("DevCCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DevCategory {
            get {
                return this.DevCategoryField;
            }
            set {
                if ((this.DevCategoryField.Equals(value) != true)) {
                    this.DevCategoryField = value;
                    this.RaisePropertyChanged("DevCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevCode {
            get {
                return this.DevCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DevCodeField, value) != true)) {
                    this.DevCodeField = value;
                    this.RaisePropertyChanged("DevCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine1 {
            get {
                return this.DevDefine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine1Field, value) != true)) {
                    this.DevDefine1Field = value;
                    this.RaisePropertyChanged("DevDefine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine10 {
            get {
                return this.DevDefine10Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine10Field, value) != true)) {
                    this.DevDefine10Field = value;
                    this.RaisePropertyChanged("DevDefine10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevDefine11 {
            get {
                return this.DevDefine11Field;
            }
            set {
                if ((this.DevDefine11Field.Equals(value) != true)) {
                    this.DevDefine11Field = value;
                    this.RaisePropertyChanged("DevDefine11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevDefine12 {
            get {
                return this.DevDefine12Field;
            }
            set {
                if ((this.DevDefine12Field.Equals(value) != true)) {
                    this.DevDefine12Field = value;
                    this.RaisePropertyChanged("DevDefine12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> DevDefine13 {
            get {
                return this.DevDefine13Field;
            }
            set {
                if ((this.DevDefine13Field.Equals(value) != true)) {
                    this.DevDefine13Field = value;
                    this.RaisePropertyChanged("DevDefine13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> DevDefine14 {
            get {
                return this.DevDefine14Field;
            }
            set {
                if ((this.DevDefine14Field.Equals(value) != true)) {
                    this.DevDefine14Field = value;
                    this.RaisePropertyChanged("DevDefine14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DevDefine15 {
            get {
                return this.DevDefine15Field;
            }
            set {
                if ((this.DevDefine15Field.Equals(value) != true)) {
                    this.DevDefine15Field = value;
                    this.RaisePropertyChanged("DevDefine15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DevDefine16 {
            get {
                return this.DevDefine16Field;
            }
            set {
                if ((this.DevDefine16Field.Equals(value) != true)) {
                    this.DevDefine16Field = value;
                    this.RaisePropertyChanged("DevDefine16");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine2 {
            get {
                return this.DevDefine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine2Field, value) != true)) {
                    this.DevDefine2Field = value;
                    this.RaisePropertyChanged("DevDefine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine3 {
            get {
                return this.DevDefine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine3Field, value) != true)) {
                    this.DevDefine3Field = value;
                    this.RaisePropertyChanged("DevDefine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine4 {
            get {
                return this.DevDefine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine4Field, value) != true)) {
                    this.DevDefine4Field = value;
                    this.RaisePropertyChanged("DevDefine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine5 {
            get {
                return this.DevDefine5Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine5Field, value) != true)) {
                    this.DevDefine5Field = value;
                    this.RaisePropertyChanged("DevDefine5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine6 {
            get {
                return this.DevDefine6Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine6Field, value) != true)) {
                    this.DevDefine6Field = value;
                    this.RaisePropertyChanged("DevDefine6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine7 {
            get {
                return this.DevDefine7Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine7Field, value) != true)) {
                    this.DevDefine7Field = value;
                    this.RaisePropertyChanged("DevDefine7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine8 {
            get {
                return this.DevDefine8Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine8Field, value) != true)) {
                    this.DevDefine8Field = value;
                    this.RaisePropertyChanged("DevDefine8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDefine9 {
            get {
                return this.DevDefine9Field;
            }
            set {
                if ((object.ReferenceEquals(this.DevDefine9Field, value) != true)) {
                    this.DevDefine9Field = value;
                    this.RaisePropertyChanged("DevDefine9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevImageUrl {
            get {
                return this.DevImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.DevImageUrlField, value) != true)) {
                    this.DevImageUrlField = value;
                    this.RaisePropertyChanged("DevImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevName {
            get {
                return this.DevNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DevNameField, value) != true)) {
                    this.DevNameField = value;
                    this.RaisePropertyChanged("DevName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevQRUrl {
            get {
                return this.DevQRUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.DevQRUrlField, value) != true)) {
                    this.DevQRUrlField = value;
                    this.RaisePropertyChanged("DevQRUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevStd {
            get {
                return this.DevStdField;
            }
            set {
                if ((object.ReferenceEquals(this.DevStdField, value) != true)) {
                    this.DevStdField = value;
                    this.RaisePropertyChanged("DevStd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((this.DeviceIdField.Equals(value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FContactsTel {
            get {
                return this.FContactsTelField;
            }
            set {
                if ((object.ReferenceEquals(this.FContactsTelField, value) != true)) {
                    this.FContactsTelField = value;
                    this.RaisePropertyChanged("FContactsTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FactoryContacts {
            get {
                return this.FactoryContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.FactoryContactsField, value) != true)) {
                    this.FactoryContactsField = value;
                    this.RaisePropertyChanged("FactoryContacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FactoryName {
            get {
                return this.FactoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FactoryNameField, value) != true)) {
                    this.FactoryNameField = value;
                    this.RaisePropertyChanged("FactoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPUrl {
            get {
                return this.IPUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.IPUrlField, value) != true)) {
                    this.IPUrlField = value;
                    this.RaisePropertyChanged("IPUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastDate {
            get {
                return this.LastDateField;
            }
            set {
                if ((this.LastDateField.Equals(value) != true)) {
                    this.LastDateField = value;
                    this.RaisePropertyChanged("LastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastPerson {
            get {
                return this.LastPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.LastPersonField, value) != true)) {
                    this.LastPersonField = value;
                    this.RaisePropertyChanged("LastPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalAddress {
            get {
                return this.LocalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalAddressField, value) != true)) {
                    this.LocalAddressField = value;
                    this.RaisePropertyChanged("LocalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialPort {
            get {
                return this.SerialPortField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialPortField, value) != true)) {
                    this.SerialPortField = value;
                    this.RaisePropertyChanged("SerialPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UseStatus {
            get {
                return this.UseStatusField;
            }
            set {
                if ((this.UseStatusField.Equals(value) != true)) {
                    this.UseStatusField = value;
                    this.RaisePropertyChanged("UseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfArrayOfMainPipelineInfodYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfArrayOfMainPipelineInfodYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRPiPeline.MainPipelineInfo[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRPiPeline.MainPipelineInfo[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CustomFaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfMainPipelineInfodYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfMainPipelineInfodYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRPiPeline.MainPipelineInfo DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRPiPeline.MainPipelineInfo Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfDevicedYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfDevicedYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRPiPeline.Device DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRPiPeline.Device Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRPiPeline.IPipelineService")]
    public interface IPipelineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetOperatingRecord", ReplyAction="http://tempuri.org/IPipelineService/GetOperatingRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRPiPeline.CustomFaultMessage), Action="http://tempuri.org/IPipelineService/GetOperatingRecordCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRPiPeline.MainPipelineInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRPiPeline.MainPipelineInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRPiPeline.Device))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRPiPeline.CommonResultOfArrayOfMainPipelineInfodYMi5huk))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRPiPeline.CustomFaultMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRPiPeline.CommonResultOfMainPipelineInfodYMi5huk))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        LY.MES.WFCL.SRPiPeline.CommonResultOfArrayOfMainPipelineInfodYMi5huk GetOperatingRecord(string sessionId, System.Tuple<string, object[]> tFilter, int CurrPage, int PageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetOperatingRecord", ReplyAction="http://tempuri.org/IPipelineService/GetOperatingRecordResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfArrayOfMainPipelineInfodYMi5huk> GetOperatingRecordAsync(string sessionId, System.Tuple<string, object[]> tFilter, int CurrPage, int PageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/AddOperatingData", ReplyAction="http://tempuri.org/IPipelineService/AddOperatingDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRPiPeline.CustomFaultMessage), Action="http://tempuri.org/IPipelineService/AddOperatingDataCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRPiPeline.CommonResultOfMainPipelineInfodYMi5huk AddOperatingData(string sessionId, LY.MES.WFCL.SRPiPeline.MainPipelineInfo model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/AddOperatingData", ReplyAction="http://tempuri.org/IPipelineService/AddOperatingDataResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfMainPipelineInfodYMi5huk> AddOperatingDataAsync(string sessionId, LY.MES.WFCL.SRPiPeline.MainPipelineInfo model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetDaviceData", ReplyAction="http://tempuri.org/IPipelineService/GetDaviceDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRPiPeline.CustomFaultMessage), Action="http://tempuri.org/IPipelineService/GetDaviceDataCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk GetDaviceData(string sessionId, string DevCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetDaviceData", ReplyAction="http://tempuri.org/IPipelineService/GetDaviceDataResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk> GetDaviceDataAsync(string sessionId, string DevCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetDaviceInformation", ReplyAction="http://tempuri.org/IPipelineService/GetDaviceInformationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRPiPeline.CustomFaultMessage), Action="http://tempuri.org/IPipelineService/GetDaviceInformationCustomFaultMessageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk GetDaviceInformation(string sessionId, string DevCCode, string DevCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetDaviceInformation", ReplyAction="http://tempuri.org/IPipelineService/GetDaviceInformationResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk> GetDaviceInformationAsync(string sessionId, string DevCCode, string DevCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPipelineServiceChannel : LY.MES.WFCL.SRPiPeline.IPipelineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PipelineServiceClient : System.ServiceModel.ClientBase<LY.MES.WFCL.SRPiPeline.IPipelineService>, LY.MES.WFCL.SRPiPeline.IPipelineService {
        
        public PipelineServiceClient() {
        }
        
        public PipelineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PipelineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PipelineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PipelineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LY.MES.WFCL.SRPiPeline.CommonResultOfArrayOfMainPipelineInfodYMi5huk GetOperatingRecord(string sessionId, System.Tuple<string, object[]> tFilter, int CurrPage, int PageSize) {
            return base.Channel.GetOperatingRecord(sessionId, tFilter, CurrPage, PageSize);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfArrayOfMainPipelineInfodYMi5huk> GetOperatingRecordAsync(string sessionId, System.Tuple<string, object[]> tFilter, int CurrPage, int PageSize) {
            return base.Channel.GetOperatingRecordAsync(sessionId, tFilter, CurrPage, PageSize);
        }
        
        public LY.MES.WFCL.SRPiPeline.CommonResultOfMainPipelineInfodYMi5huk AddOperatingData(string sessionId, LY.MES.WFCL.SRPiPeline.MainPipelineInfo model) {
            return base.Channel.AddOperatingData(sessionId, model);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfMainPipelineInfodYMi5huk> AddOperatingDataAsync(string sessionId, LY.MES.WFCL.SRPiPeline.MainPipelineInfo model) {
            return base.Channel.AddOperatingDataAsync(sessionId, model);
        }
        
        public LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk GetDaviceData(string sessionId, string DevCode) {
            return base.Channel.GetDaviceData(sessionId, DevCode);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk> GetDaviceDataAsync(string sessionId, string DevCode) {
            return base.Channel.GetDaviceDataAsync(sessionId, DevCode);
        }
        
        public LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk GetDaviceInformation(string sessionId, string DevCCode, string DevCode) {
            return base.Channel.GetDaviceInformation(sessionId, DevCCode, DevCode);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRPiPeline.CommonResultOfDevicedYMi5huk> GetDaviceInformationAsync(string sessionId, string DevCCode, string DevCode) {
            return base.Channel.GetDaviceInformationAsync(sessionId, DevCCode, DevCode);
        }
    }
}
