//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用于工艺参数、设备参数、工艺配方参数进行对照  
    /// </summary>  
    public partial class CraftsParameterContrast
    {
    	/// <summary>  
    	/// 参数名称  
    	/// </summary>  
        public string ParamName { get; set; }
    	/// <summary>  
    	/// 设备参数名称  
    	/// </summary>  
        public string DevepName { get; set; }
    	/// <summary>  
    	/// 参数类型  
    	/// </summary>  
        public string ParamType { get; set; }
    	/// <summary>  
    	/// 自动编号  
    	/// </summary>  
        public int ParameterID { get; set; }
    }
}
