//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 工艺流程参数设置子表  
    /// </summary>  
    public partial class CraftsLineParamSetDetail
    {
    	/// <summary>  
    	/// 自动编号  
    	/// </summary>  
        public int AutoID { get; set; }
    	/// <summary>  
    	/// 主表ID  
    	/// </summary>  
        public Nullable<int> ID { get; set; }
    	/// <summary>  
    	/// 优先级  
    	/// </summary>  
        public int Priority { get; set; }
    	/// <summary>  
    	/// 标准值  
    	/// </summary>  
        public string StandardValue { get; set; }
    	/// <summary>  
    	/// 上限值  
    	/// </summary>  
        public string UpperValue { get; set; }
    	/// <summary>  
    	/// 下限值  
    	/// </summary>  
        public string LowerValue { get; set; }
    	/// <summary>  
    	/// 阀门检查  
    	/// </summary>  
        public bool IsValveCheck { get; set; }
    	/// <summary>  
    	/// 阀门控制  
    	/// </summary>  
        public bool IsValveControl { get; set; }
    	/// <summary>  
    	/// 是否固定参数  
    	/// </summary>  
        public bool IsFixedParameters { get; set; }
    	/// <summary>  
    	/// 间隔时长(秒)  
    	/// </summary>  
        public Nullable<int> IntervalDuration { get; set; }
    	/// <summary>  
    	/// 触发时长(分钟)  
    	/// </summary>  
        public Nullable<int> TriggerDuration { get; set; }
    	/// <summary>  
    	/// 使用状态  
    	/// </summary>  
        public string UserStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> CraftsID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int ParameterID { get; set; }
    
        public virtual CraftsLineParamSet CraftsLineParamSet { get; set; }
    }
}
