//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 部门档案  
    /// </summary>  
    public partial class Department
    {
    	/// <summary>  
    	/// 部门编码  
    	/// </summary>  
        public string DepCode { get; set; }
    	/// <summary>  
    	/// 部门名称  
    	/// </summary>  
        public string DepName { get; set; }
    	/// <summary>  
    	/// 父级部门编码  
    	/// </summary>  
        public string SupDepCode { get; set; }
    	/// <summary>  
    	/// 负责人编码  
    	/// </summary>  
        public string DepPerson { get; set; }
    	/// <summary>  
    	/// 电话  
    	/// </summary>  
        public string DepPhone { get; set; }
    	/// <summary>  
    	/// 地址  
    	/// </summary>  
        public string DepAddress { get; set; }
    	/// <summary>  
    	/// 传真  
    	/// </summary>  
        public string DepFax { get; set; }
    	/// <summary>  
    	/// 邮政编码  
    	/// </summary>  
        public string DepPostCode { get; set; }
    	/// <summary>  
    	/// 电子右键  
    	/// </summary>  
        public string DepEmail { get; set; }
    	/// <summary>  
    	/// 备注  
    	/// </summary>  
        public string DepMemo { get; set; }
    	/// <summary>  
    	/// 成立日期  
    	/// </summary>  
        public System.DateTime DepBeginDate { get; set; }
    	/// <summary>  
    	/// 撤销日期  
    	/// </summary>  
        public Nullable<System.DateTime> DepEndDate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int Grade { get; set; }
    }
}
