//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    ///   
    /// </summary>  
    public partial class DeviceClass
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string SupCCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int Grade { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string Remark { get; set; }
    }
}
