//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 记录设备执行接口信息  
    /// </summary>  
    public partial class DeviceExecute
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public int DeveCode { get; set; }
    	/// <summary>  
    	/// 设备编码  
    	/// </summary>  
        public string DevCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DeviCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> CollFrequency { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int UserStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public System.DateTime CreateDate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CreatePerson { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> LastDate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string LastPerson { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevpCode { get; set; }
    }
}
