//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 记录与设备相关的接口信息  
    /// </summary>  
    public partial class DeviceInterface
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DeviCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DeviName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevpCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> DevpAddress { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DataType { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<bool> IsTwoWay { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string SendFormat { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string Remark { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int UserStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> ConAccAddress { get; set; }
    }
}
