//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 记录设备信息  
    /// </summary>  
    public partial class Device
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevStd { get; set; }
    	/// <summary>  
    	/// 设备分类编码  
    	/// </summary>  
        public string DevCCode { get; set; }
    	/// <summary>  
    	/// 设备图片地址  
    	/// </summary>  
        public string DevImageUrl { get; set; }
    	/// <summary>  
    	/// 设备二维码地址  
    	/// </summary>  
        public string DevQRUrl { get; set; }
    	/// <summary>  
    	/// 设备类别  
    	/// </summary>  
        public int DevCategory { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string FactoryName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string FactoryContacts { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string FContactsTel { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string Origin { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string IPUrl { get; set; }
    	/// <summary>  
    	/// IP端口  
    	/// </summary>  
        public Nullable<int> Port { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string SerialPort { get; set; }
    	/// <summary>  
    	/// 设备Id  
    	/// </summary>  
        public Nullable<int> DeviceId { get; set; }
    	/// <summary>  
    	/// 访问ID地址  
    	/// </summary>  
        public Nullable<int> CallID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string LocalAddress { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string AdminPerson { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string AdminPhone { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int UseStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string Remark { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public System.DateTime CreateDate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CreatePerson { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> LastDate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string LastPerson { get; set; }
    	/// <summary>  
    	/// 设备简称  
    	/// </summary>  
        public string DevAbbName { get; set; }
    	/// <summary>  
    	/// 重量(KG)  
    	/// </summary>  
        public Nullable<decimal> Weight { get; set; }
    	/// <summary>  
    	/// 体积  
    	/// </summary>  
        public Nullable<decimal> Volume { get; set; }
    	/// <summary>  
    	/// 设备自定义2  
    	/// </summary>  
        public string DevDefine2 { get; set; }
    	/// <summary>  
    	/// 设备自定义3  
    	/// </summary>  
        public string DevDefine3 { get; set; }
    	/// <summary>  
    	/// 设备自定义4  
    	/// </summary>  
        public string DevDefine4 { get; set; }
    	/// <summary>  
    	/// 设备自定义5  
    	/// </summary>  
        public string DevDefine5 { get; set; }
    	/// <summary>  
    	/// 设备自定义6  
    	/// </summary>  
        public string DevDefine6 { get; set; }
    	/// <summary>  
    	/// 设备自定义7  
    	/// </summary>  
        public string DevDefine7 { get; set; }
    	/// <summary>  
    	/// 设备自定义9  
    	/// </summary>  
        public string DevDefine9 { get; set; }
    	/// <summary>  
    	/// 设备自定义10  
    	/// </summary>  
        public string DevDefine10 { get; set; }
    	/// <summary>  
    	/// 设备自定义11  
    	/// </summary>  
        public Nullable<int> DevDefine11 { get; set; }
    	/// <summary>  
    	/// 设备自定义12  
    	/// </summary>  
        public Nullable<int> DevDefine12 { get; set; }
    	/// <summary>  
    	/// 设备自定义13  
    	/// </summary>  
        public Nullable<double> DevDefine13 { get; set; }
    	/// <summary>  
    	/// 设备自定义14  
    	/// </summary>  
        public Nullable<double> DevDefine14 { get; set; }
    	/// <summary>  
    	/// 设备自定义15  
    	/// </summary>  
        public Nullable<System.DateTime> DevDefine15 { get; set; }
    	/// <summary>  
    	/// 设备自定义16  
    	/// </summary>  
        public Nullable<System.DateTime> DevDefine16 { get; set; }
    	/// <summary>  
    	/// 设备自定义8  
    	/// </summary>  
        public string DevDefine8 { get; set; }
    	/// <summary>  
    	/// 设备自定义1  
    	/// </summary>  
        public string DevDefine1 { get; set; }
    }
}
