//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 记录设备相关的参数信息  
    /// </summary>  
    public partial class DeviceParameter
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevpCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevpName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> StandardValue { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> MinValue { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> MaxValue { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string Remark { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string SerialPort { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string BaudRate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CheckBit { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DataBit { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string StopBit { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ConvertType { get; set; }
    }
}
