//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    ///   
    /// </summary>  
    public partial class IPRegistForm
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public int ID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string IP { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string MACAddress { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int Status { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CreatorName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public System.DateTime CreatorTime { get; set; }
    }
}
