//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    ///   
    /// </summary>  
    public partial class MainPipelineInfo
    {
    	/// <summary>  
    	/// 自动编号  
    	/// </summary>  
        public int AutoID { get; set; }
    	/// <summary>  
    	/// 管道编号  
    	/// </summary>  
        public string DeveCode { get; set; }
    	/// <summary>  
    	/// 管道名称  
    	/// </summary>  
        public string DeveName { get; set; }
    	/// <summary>  
    	/// 管道阀门状态  
    	/// </summary>  
        public string PipelineStatus { get; set; }
    	/// <summary>  
    	/// 提示说明  
    	/// </summary>  
        public string PromptDes { get; set; }
    	/// <summary>  
    	/// 班次  
    	/// </summary>  
        public string Frequency { get; set; }
    	/// <summary>  
    	/// 操作说明  
    	/// </summary>  
        public string OperatorReamrk { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>  
        public Nullable<System.DateTime> CreateDate { get; set; }
    	/// <summary>  
    	/// 创建人  
    	/// </summary>  
        public string Creator { get; set; }
    	/// <summary>  
    	/// 操作  
    	/// </summary>  
        public string Operator { get; set; }
    	/// <summary>  
    	/// 操作时间  
    	/// </summary>  
        public Nullable<System.DateTime> OperatingTime { get; set; }
    }
}
