//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LYMesSystemEntities : DbContext
    {
        public LYMesSystemEntities()
            : base("name=LYMesSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArrangedVouch> ArrangedVouch { get; set; }
        public virtual DbSet<ArrangedVouchLog> ArrangedVouchLog { get; set; }
        public virtual DbSet<CollectDataInfo> CollectDataInfo { get; set; }
        public virtual DbSet<CraftsLineParamSet> CraftsLineParamSet { get; set; }
        public virtual DbSet<CraftsLineParamSetDetail> CraftsLineParamSetDetail { get; set; }
        public virtual DbSet<CraftsParameterContrast> CraftsParameterContrast { get; set; }
        public virtual DbSet<CraftsProcessExecute> CraftsProcessExecute { get; set; }
        public virtual DbSet<CraftsProcessExecuteDetail> CraftsProcessExecuteDetail { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceClass> DeviceClass { get; set; }
        public virtual DbSet<DeviceExecute> DeviceExecute { get; set; }
        public virtual DbSet<DeviceInterface> DeviceInterface { get; set; }
        public virtual DbSet<DeviceParameter> DeviceParameter { get; set; }
        public virtual DbSet<MainPipelineInfo> MainPipelineInfo { get; set; }
        public virtual DbSet<QC_PullDetectionReg> QC_PullDetectionReg { get; set; }
        public virtual DbSet<vw_DurmsUpFeeding> vw_DurmsUpFeeding { get; set; }
        public virtual DbSet<vw_QC_FindLeakDrumsSet> vw_QC_FindLeakDrumsSet { get; set; }
        public virtual DbSet<QC_FindLeakDrumsSet> QC_FindLeakDrumsSet { get; set; }
        public virtual DbSet<QC_FindLeakDrumsSetDetail> QC_FindLeakDrumsSetDetail { get; set; }
        public virtual DbSet<QC_DrumsFindLeakReport> QC_DrumsFindLeakReport { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DeviceWorkingCondition> DeviceWorkingCondition { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<vw_ArrangedCraftsProcessExecute> vw_ArrangedCraftsProcessExecute { get; set; }
        public virtual DbSet<IPRegistForm> IPRegistForm { get; set; }
        public virtual DbSet<vw_CraftsLineParamSetDetail> vw_CraftsLineParamSetDetail { get; set; }
        public virtual DbSet<V_DV_DevExecute> V_DV_DevExecute { get; set; }
    }
}
