//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 职员档案  
    /// </summary>  
    public partial class Person
    {
    	/// <summary>  
    	/// 职员编码  
    	/// </summary>  
        public string PersonCode { get; set; }
    	/// <summary>  
    	/// 姓名  
    	/// </summary>  
        public string PersonName { get; set; }
    	/// <summary>  
    	/// 职员类别  
    	/// </summary>  
        public string PersonType { get; set; }
    	/// <summary>  
    	/// 部门编码  
    	/// </summary>  
        public string DepCode { get; set; }
    	/// <summary>  
    	/// 电子邮件  
    	/// </summary>  
        public string PersonEmai { get; set; }
    	/// <summary>  
    	/// 电话  
    	/// </summary>  
        public string PersonPhone { get; set; }
    	/// <summary>  
    	/// 性别  
    	/// </summary>  
        public string Sex { get; set; }
    	/// <summary>  
    	/// 是否操作员  
    	/// </summary>  
        public bool IsOperator { get; set; }
    	/// <summary>  
    	/// 操作员编码  
    	/// </summary>  
        public string OparatorCode { get; set; }
    	/// <summary>  
    	/// 操作员名称  
    	/// </summary>  
        public string OparatorName { get; set; }
    	/// <summary>  
    	/// 身高(CM)  
    	/// </summary>  
        public Nullable<int> Height { get; set; }
    	/// <summary>  
    	/// 重量(KG)  
    	/// </summary>  
        public Nullable<decimal> Weight { get; set; }
    }
}
