//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 转鼓漏检报告  
    /// </summary>  
    public partial class QC_DrumsFindLeakReport
    {
    	/// <summary>  
    	/// 漏检单号  
    	/// </summary>  
        public string FLVCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int Year { get; set; }
    	/// <summary>  
    	/// 月份  
    	/// </summary>  
        public int Month { get; set; }
    	/// <summary>  
    	/// 周次  
    	/// </summary>  
        public int Week { get; set; }
    	/// <summary>  
    	/// 转鼓编码  
    	/// </summary>  
        public string DevCode { get; set; }
    	/// <summary>  
    	/// 转鼓名称  
    	/// </summary>  
        public string DevName { get; set; }
    	/// <summary>  
    	/// 班次  
    	/// </summary>  
        public string Frequency { get; set; }
    	/// <summary>  
    	/// 检漏情况  
    	/// </summary>  
        public string FLSituation { get; set; }
    	/// <summary>  
    	/// 检漏结果  
    	/// </summary>  
        public string FLResult { get; set; }
    	/// <summary>  
    	/// 补充说明  
    	/// </summary>  
        public string Remark { get; set; }
    	/// <summary>  
    	/// 创建人  
    	/// </summary>  
        public string CreatePerson { get; set; }
    	/// <summary>  
    	/// 创建日期  
    	/// </summary>  
        public System.DateTime CreateDate { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>  
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 来源单号  
    	/// </summary>  
        public string SourceCode { get; set; }
    }
}
