//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用于质检针对索戴的拉力做检测的记录  
    /// </summary>  
    public partial class QC_PullDetectionReg
    {
    	/// <summary>  
    	/// 自动编号  
    	/// </summary>  
        public int AutoID { get; set; }
    	/// <summary>  
    	/// 登记日期  
    	/// </summary>  
        public System.DateTime RegDate { get; set; }
    	/// <summary>  
    	/// 班次  
    	/// </summary>  
        public string Frequency { get; set; }
    	/// <summary>  
    	/// 产线  
    	/// </summary>  
        public string ProductionLine { get; set; }
    	/// <summary>  
    	/// 质检员  
    	/// </summary>  
        public string QualityInspector { get; set; }
    	/// <summary>  
    	/// 订单类型  
    	/// </summary>  
        public string OrderType { get; set; }
    	/// <summary>  
    	/// 生产订单号  
    	/// </summary>  
        public string OrderCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ProductLevel { get; set; }
    	/// <summary>  
    	/// 标准拉力  
    	/// </summary>  
        public Nullable<decimal> StandardPull { get; set; }
    	/// <summary>  
    	/// 实际拉力  
    	/// </summary>  
        public Nullable<decimal> ActualPull { get; set; }
    	/// <summary>  
    	/// 实际宽度  
    	/// </summary>  
        public Nullable<decimal> ActualWidth { get; set; }
    	/// <summary>  
    	/// 实际厚度  
    	/// </summary>  
        public Nullable<decimal> ActualThick { get; set; }
    	/// <summary>  
    	/// 订单宽度  
    	/// </summary>  
        public Nullable<decimal> Width { get; set; }
    	/// <summary>  
    	/// 订单厚度  
    	/// </summary>  
        public Nullable<decimal> Thick { get; set; }
    	/// <summary>  
    	/// 强度  
    	/// </summary>  
        public string Strength { get; set; }
    	/// <summary>  
    	/// 处理类型(勤哲,非勤哲)  
    	/// </summary>  
        public int ProcessType { get; set; }
    	/// <summary>  
    	/// 检测结果  
    	/// </summary>  
        public string TestResults { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>  
        public System.DateTime CreateDate { get; set; }
    	/// <summary>  
    	/// 创建人  
    	/// </summary>  
        public string CreatePerson { get; set; }
    	/// <summary>  
    	/// 修改时间  
    	/// </summary>  
        public Nullable<System.DateTime> ModifyDate { get; set; }
    	/// <summary>  
    	/// 修改人  
    	/// </summary>  
        public string ModifyPerson { get; set; }
    }
}
