//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// System.Data.SqlClient  
    /// </summary>  
    public partial class V_DV_DevExecute
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public int ExecuteID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ZGCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ZGName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DeviCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevpCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DeviName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevpName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> CollFrequency { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string IPUrl { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> Port { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string LocalAddress { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> MaxValue { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> MinValue { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> StandardValue { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> DeviceId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> CallID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> DevpAddress { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string SendFormat { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string SerialPort { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string BaudRate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CheckBit { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DataBit { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string StopBit { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int InterFaceStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DataType { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevStd { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int EquipStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int WorkStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> ConAccAddress { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ConvertType { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCode { get; set; }
    }
}
