//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// System.Data.SqlClient  
    /// </summary>  
    public partial class vw_DurmsUpFeeding
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public long vwId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int DeveUseStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> ExecuteID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> ExecuteOrder { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string WorkshopCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string WorkshopName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string WorkbrachCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string WorkbrachName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CraftsCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CraftsName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ExecuteMode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> PlanDuration { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> StartTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> EndTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> ExecuteStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> ID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ArrangedVouchCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> VouchDate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string MaterialVouchCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string FormulaCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string FormulaName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> InputWeight { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> OutputWeight { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<decimal> WeighingPounds { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<int> UserStatus { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string InterruptionRemark { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> InterruptionTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string Creator { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ModifyPerson { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<System.DateTime> ModifyTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string LicenseNum { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<double> VehicleWeight { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public Nullable<double> WeightMan { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string TeachProgress { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string RFIDCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ProPlanNum { get; set; }
    }
}
