//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// System.Data.SqlClient  
    /// </summary>  
    public partial class vw_QC_FindLeakDrumsSet
    {
    	/// <summary>  
    	///   
    	/// </summary>  
        public int AutoID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int ID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int Year { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int Month { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int Week { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string Frequency { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string CreatePerson { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public System.DateTime CreateDate { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public System.DateTime CreateDateTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string DevName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int IsLeak { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public string ArrangedVouchCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>  
        public int ExecuteID { get; set; }
    }
}
