//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MES.WFCL.SRBase {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CraftsParameterContrast", Namespace="http://schemas.datacontract.org/2004/07/LY.MES.Model")]
    [System.SerializableAttribute()]
    public partial class CraftsParameterContrast : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParameterIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevepName {
            get {
                return this.DevepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DevepNameField, value) != true)) {
                    this.DevepNameField = value;
                    this.RaisePropertyChanged("DevepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParamName {
            get {
                return this.ParamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamNameField, value) != true)) {
                    this.ParamNameField = value;
                    this.RaisePropertyChanged("ParamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParamType {
            get {
                return this.ParamTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamTypeField, value) != true)) {
                    this.ParamTypeField = value;
                    this.RaisePropertyChanged("ParamType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParameterID {
            get {
                return this.ParameterIDField;
            }
            set {
                if ((this.ParameterIDField.Equals(value) != true)) {
                    this.ParameterIDField = value;
                    this.RaisePropertyChanged("ParameterID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfCraftsParameterContrastdYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfCraftsParameterContrastdYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRBase.CraftsParameterContrast DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRBase.CraftsParameterContrast Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CustomFaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResultOfArrayOfCraftsParameterContrastdYMi5huk", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResultOfArrayOfCraftsParameterContrastdYMi5huk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LY.MES.WFCL.SRBase.CraftsParameterContrast[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LY.MES.WFCL.SRBase.CraftsParameterContrast[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNum {
            get {
                return this.TotalNumField;
            }
            set {
                if ((this.TotalNumField.Equals(value) != true)) {
                    this.TotalNumField = value;
                    this.RaisePropertyChanged("TotalNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRBase.IBaseService")]
    public interface IBaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/AddCraftsParameterContrast", ReplyAction="http://tempuri.org/IBaseService/AddCraftsParameterContrastResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRBase.CustomFaultMessage), Action="http://tempuri.org/IBaseService/AddCraftsParameterContrastCustomFaultMessageFault" +
            "", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk AddCraftsParameterContrast(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/AddCraftsParameterContrast", ReplyAction="http://tempuri.org/IBaseService/AddCraftsParameterContrastResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk> AddCraftsParameterContrastAsync(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/UpdateCraftsParameterContrast", ReplyAction="http://tempuri.org/IBaseService/UpdateCraftsParameterContrastResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRBase.CustomFaultMessage), Action="http://tempuri.org/IBaseService/UpdateCraftsParameterContrastCustomFaultMessageFa" +
            "ult", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk UpdateCraftsParameterContrast(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/UpdateCraftsParameterContrast", ReplyAction="http://tempuri.org/IBaseService/UpdateCraftsParameterContrastResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk> UpdateCraftsParameterContrastAsync(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/GetCraftsParameterContrastListByID", ReplyAction="http://tempuri.org/IBaseService/GetCraftsParameterContrastListByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRBase.CustomFaultMessage), Action="http://tempuri.org/IBaseService/GetCraftsParameterContrastListByIDCustomFaultMess" +
            "ageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk GetCraftsParameterContrastListByID(string sessionId, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/GetCraftsParameterContrastListByID", ReplyAction="http://tempuri.org/IBaseService/GetCraftsParameterContrastListByIDResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk> GetCraftsParameterContrastListByIDAsync(string sessionId, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/DelCraftsParameterContrastListByID", ReplyAction="http://tempuri.org/IBaseService/DelCraftsParameterContrastListByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRBase.CustomFaultMessage), Action="http://tempuri.org/IBaseService/DelCraftsParameterContrastListByIDCustomFaultMess" +
            "ageFault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        Client.Utility.SRSysBase.CommonResultOfboolean DelCraftsParameterContrastListByID(string sessionId, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/DelCraftsParameterContrastListByID", ReplyAction="http://tempuri.org/IBaseService/DelCraftsParameterContrastListByIDResponse")]
        System.Threading.Tasks.Task<Client.Utility.SRSysBase.CommonResultOfboolean> DelCraftsParameterContrastListByIDAsync(string sessionId, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/GetCraftsParameterContrastList", ReplyAction="http://tempuri.org/IBaseService/GetCraftsParameterContrastListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LY.MES.WFCL.SRBase.CustomFaultMessage), Action="http://tempuri.org/IBaseService/GetCraftsParameterContrastListCustomFaultMessageF" +
            "ault", Name="CustomFaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Server.Utility")]
        LY.MES.WFCL.SRBase.CommonResultOfArrayOfCraftsParameterContrastdYMi5huk GetCraftsParameterContrastList(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/GetCraftsParameterContrastList", ReplyAction="http://tempuri.org/IBaseService/GetCraftsParameterContrastListResponse")]
        System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfArrayOfCraftsParameterContrastdYMi5huk> GetCraftsParameterContrastListAsync(string sessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaseServiceChannel : LY.MES.WFCL.SRBase.IBaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaseServiceClient : System.ServiceModel.ClientBase<LY.MES.WFCL.SRBase.IBaseService>, LY.MES.WFCL.SRBase.IBaseService {
        
        public BaseServiceClient() {
        }
        
        public BaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk AddCraftsParameterContrast(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model) {
            return base.Channel.AddCraftsParameterContrast(sessionId, model);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk> AddCraftsParameterContrastAsync(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model) {
            return base.Channel.AddCraftsParameterContrastAsync(sessionId, model);
        }
        
        public LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk UpdateCraftsParameterContrast(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model) {
            return base.Channel.UpdateCraftsParameterContrast(sessionId, model);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk> UpdateCraftsParameterContrastAsync(string sessionId, LY.MES.WFCL.SRBase.CraftsParameterContrast model) {
            return base.Channel.UpdateCraftsParameterContrastAsync(sessionId, model);
        }
        
        public LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk GetCraftsParameterContrastListByID(string sessionId, int ID) {
            return base.Channel.GetCraftsParameterContrastListByID(sessionId, ID);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfCraftsParameterContrastdYMi5huk> GetCraftsParameterContrastListByIDAsync(string sessionId, int ID) {
            return base.Channel.GetCraftsParameterContrastListByIDAsync(sessionId, ID);
        }
        
        public Client.Utility.SRSysBase.CommonResultOfboolean DelCraftsParameterContrastListByID(string sessionId, int ID) {
            return base.Channel.DelCraftsParameterContrastListByID(sessionId, ID);
        }
        
        public System.Threading.Tasks.Task<Client.Utility.SRSysBase.CommonResultOfboolean> DelCraftsParameterContrastListByIDAsync(string sessionId, int ID) {
            return base.Channel.DelCraftsParameterContrastListByIDAsync(sessionId, ID);
        }
        
        public LY.MES.WFCL.SRBase.CommonResultOfArrayOfCraftsParameterContrastdYMi5huk GetCraftsParameterContrastList(string sessionId) {
            return base.Channel.GetCraftsParameterContrastList(sessionId);
        }
        
        public System.Threading.Tasks.Task<LY.MES.WFCL.SRBase.CommonResultOfArrayOfCraftsParameterContrastdYMi5huk> GetCraftsParameterContrastListAsync(string sessionId) {
            return base.Channel.GetCraftsParameterContrastListAsync(sessionId);
        }
    }
}
